### ISSUE TITLE
马2进3 错误

### ISSUE THREAD

**Issue by skarl-api** [walker8088/cchess#6]
board.move_chinese("马2进3") 无法运行 代码内部有多处错误

**Comment by walker8088** [comment]
请把您的代码贴一下，board默认初始化的fen串一般是默认红方走子，您这个代码是黑方走子，是不是这个原因？如果还有错误，麻烦也请贴一下，谢谢。

**Comment by skarl-api** [comment]
错误已经解除，几个部分的问题 第一个部分问题是 self变量问题我已经修改了源码 第二部是 数字没有转全角数字
